gamma = 910.0
theta = 4.5
e0 = 16980.0
kappa = 0.22
time_step = 0.0005
n_time = 200
el_reach = 20000.0
m = 1.52
n = 1.33
raman_start = 0.0
raman_end = 2500.0
raman_step = 2.0
raman_res = 20.0
temp = 298.0
convergence = 1.0
boltz_toggle = false
